export const singout = <i className="fa-solid fa-gear"></i>;
export const calender = <i className="fa-solid fa-calendar-days"></i>;
export const chart = <i className="fa-solid fa-chart-simple"></i>;
export const dollarSign = <i className="fa-solid fa-dollar-sign"></i>
export const dateSign = <i className="fa-solid fa-calendar-day"></i>
export const typeSign = <i className="fa-solid fa-sack-dollar"></i>
export const noteSign = <i className="fa-solid fa-note-sticky"></i>
export const trashBin = <i className="fa-solid fa-trash"></i>
export const addSign = <i className="fa-solid fa-plus"></i>
export const upArrowSign = <i className="fa-solid fa-circle-up"></i>
export const downArrowSign = <i className="fa-solid fa-circle-down"></i>
export const logOutSign = <i className="fa-solid fa-right-from-bracket"></i>
export const noSign = <i className="fa-solid fa-xmark"></i>
export const yesSign = <i className="fa-solid fa-check"></i>
export const childSign = <i className="fa-solid fa-children"></i>
export const newChildSign = <i className="fa-solid fa-child-reaching"></i>
export const salarySign = <i className="fa-solid fa-sack-dollar"></i>
export const giftSign = <i className="fa-solid fa-gift"></i>
export const refundSign = <i className="fa-solid fa-file-invoice-dollar"></i>
export const stockSign = <i className="fa-solid fa-arrow-trend-up"></i>
export const cryptoSign = <i className="fa-brands fa-bitcoin"></i>
export const soldSign = <i className="fa-solid fa-hand-holding-dollar"></i>
export const liquidationSign = <i className="fa-solid fa-house"></i>
export const fastfoodSign = <i className="fa-solid fa-burger"></i>
export const groceriesSign = <i className="fa-solid fa-basket-shopping"></i>
export const gasSign = <i className="fa-solid fa-gas-pump"></i>
export const healthSign = <i className="fa-regular fa-heart"></i>
export const onlinePurchaseSign = <i className="fa-regular fa-credit-card"></i>
export const membershipSign = <i className="fa-solid fa-award"></i>
export const schoolSign = <i className="fa-solid fa-school"></i>
export const travelSign = <i className="fa-solid fa-plane"></i>
export const miscSign = <i className="fa-solid fa-dollar-sign"></i>
export const babySign = <i className="fa-solid fa-child"></i>
export const emailSign = <i className="fa-regular fa-envelope"></i>
